import pandas as pd, numpy as np
import statsmodels.formula.api as smf
from scipy import stats
import warnings; warnings.filterwarnings('ignore')
W=pd.read_pickle('./wide.pkl')
W2=pd.read_pickle('./W2.pkl')  # has morph index
W['morph']=W2.morph; W['fam']=W.Family_name.fillna('ISOLATE_'+W.index.to_series())
# depth proxy: share of all features answered (not ? / not NA)
allf=[c for c in W.columns if c.startswith('GB')]
W['depth']=W[allf].isin(['0','1','2','3']).sum(1)/len(allf)
W['qshare']=(W[allf]=='?').sum(1)/len(allf)
L=pd.read_csv('DATA/grambank/cldf/languages.csv',dtype=str).set_index('ID')
W['semitic']=L.lineage.reindex(W.index).fillna('').str.contains('Semitic',case=False)
print("Semitic languages:",W.semitic.sum())
rng=np.random.default_rng(7)
def test(df,label,x='GB147',y='GB155',q155=False,q147=False):
    d=df.copy()
    if q155: d[y]=d[y].replace('?','0')
    if q147: d[x]=d[x].replace('?','0')
    d=d[d[x].isin(['0','1'])&d[y].isin(['0','1'])].copy(); d['x']=(d[x]=='1').astype(int); d['y']=(d[y]=='1').astype(int)
    a=((d.x==1)&(d.y==1)).sum();b=((d.x==1)&(d.y==0)).sum();c=((d.x==0)&(d.y==1)).sum();dd=((d.x==0)&(d.y==0)).sum()
    OR=a*dd/max(b*c,.5)
    ORs=[]
    for i in range(300):
        s=d.iloc[rng.permutation(len(d))].drop_duplicates('fam')
        aa=((s.x==1)&(s.y==1)).sum();bb=((s.x==1)&(s.y==0)).sum();cc=((s.x==0)&(s.y==1)).sum();de=((s.x==0)&(s.y==0)).sum()
        ORs.append((aa+.5)*(de+.5)/((bb+.5)*(cc+.5)))
    dm=d.dropna(subset=['morph','Macroarea'])
    try:
        m=smf.logit('y ~ x + morph + C(Macroarea)',dm).fit(disp=0,cov_type='cluster',cov_kwds={'groups':pd.factorize(dm.fam)[0]})
        adj=f"adjOR(morph+area,clusterSE)={np.exp(m.params['x']):.2f} [{np.exp(m.conf_int().loc['x',0]):.2f},{np.exp(m.conf_int().loc['x',1]):.2f}] p={m.pvalues['x']:.0e}"
    except Exception as e: adj='adj fail '+str(e)[:40]
    print(f"{label:45s} n={len(d):4d} P(c|p)={a/(a+b):.3f} P(c|~p)={c/(c+dd):.3f} rawOR={OR:5.2f} 1/fam medOR={np.median(ORs):5.2f} [{np.percentile(ORs,2.5):.2f},{np.percentile(ORs,97.5):.2f}]  {adj}")
print("\n=== 7. Break tests (GB147 -> GB155) ===")
test(W,'baseline')
big3=W.Family_name.value_counts().index[:3].tolist(); print("largest 3 families:",big3)
test(W[~W.Family_name.isin(big3)],'drop 3 largest families')
test(W[~W.Family_name.isin(W.Family_name.value_counts().index[:6].tolist())],'drop 6 largest families')
test(W[W.Macroarea!='Eurasia'],'drop Eurasia')
test(W[W.Macroarea!='Africa'],'drop Africa')
test(W[W.Macroarea!='Papunesia'],'drop Papunesia')
test(W[~W.semitic],'drop Semitic')
test(W[W.Family_name!='Afro-Asiatic'],'drop Afro-Asiatic')
test(W[W.Family_name!='Indo-European'],'drop Indo-European')
test(W,"'?' on GB155 -> 0",q155=True)
test(W,"'?' on GB147 -> 0",q147=True)
test(W,"'?' on both -> 0",q155=True,q147=True)
test(W[W.level=='language'],'languages only (no dialects)')
test(W[W.GB302=='0'],'restrict to GB302=0 (no free passive)')
test(W[W.GB302.isin(['0','1'])],'restrict to GB302 coded')
test(W[W.depth>=W.depth.median()],'well-described half (depth>=median)')
test(W[W.depth<W.depth.median()],'poorly-described half')
test(W[W.GB113=='0'],'restrict GB113=0 (no transitivizer affix)')
test(W[W.GB113=='1'],'restrict GB113=1')
test(W[W.GB114=='0'],'restrict no bound reflexive')
test(W[W.GB115=='0'],'restrict no bound reciprocal')
test(W[(W.GB103=='0')&(W.GB104=='0')],'restrict no applicative')
test(W[W.GB080=='0'],'restrict verbs have NO suffixes (GB080=0)')
test(W[W.GB079=='0'],'restrict verbs have NO prefixes (GB079=0)')
print("\n--- per macroarea ---")
for ma,g in W.groupby('Macroarea'): test(g,f'  {ma}')
print("\n--- description depth as covariate ---")
d=W[W.GB147.isin(['0','1'])&W.GB155.isin(['0','1'])].dropna(subset=['morph','Macroarea']).copy(); d['x']=(d.GB147=='1').astype(int); d['y']=(d.GB155=='1').astype(int)
m=smf.logit('y ~ x + morph + depth + C(Macroarea)',d).fit(disp=0,cov_type='cluster',cov_kwds={'groups':pd.factorize(d.fam)[0]})
print("x OR=%.2f p=%.0e; depth OR=%.2f p=%.2f"%(np.exp(m.params['x']),m.pvalues['x'],np.exp(m.params['depth']),m.pvalues['depth']))
print("\n=== Same tests for GB302 (free passive) -> GB155 ===")
test(W,'baseline GB302',x='GB302')
test(W[~W.Family_name.isin(big3)],'drop 3 largest',x='GB302')
test(W[W.Macroarea!='Eurasia'],'drop Eurasia',x='GB302')
test(W[W.Family_name!='Indo-European'],'drop Indo-European',x='GB302')
test(W[W.GB147=='0'],'restrict GB147=0',x='GB302')
test(W[W.GB080=='1'],'restrict verbs DO have suffixes',x='GB302')
test(W,"'?' GB155->0",x='GB302',q155=True)
for ma,g in W.groupby('Macroarea'): test(g,f'  {ma}',x='GB302')
# is GB302 effect just 'analytic language'? morph index distribution
dd=W[W.GB302.isin(['0','1'])].dropna(subset=['morph'])
print("morph index mean: GB302=1: %.2f  GB302=0: %.2f"%(dd[dd.GB302=='1'].morph.mean(),dd[dd.GB302=='0'].morph.mean()))
print("GB302=1 languages by family (top):",W[W.GB302=='1'].Family_name.value_counts().head(8).to_dict())
