// Enumerate free polyhexes (LAT=6) or free polyiamonds (LAT=3) with n cells
// (Redelmeier for fixed forms + canonical form under the 12-element lattice group),
// and count those whose cell-adjacency graph (inner dual) has a Hamiltonian path / Hamiltonian cycle.
//
// Coordinates: axial (a,b) on the triangular point lattice with basis e1=(1,0), e2=(1/2,sqrt3/2).
//   LAT=6: hexagon centres = all integer (a,b); neighbours (+-1,0),(0,+-1),(1,-1),(-1,1).
//   LAT=3: triangle t is represented by 3*centroid: up-triangle (a,b) with a=b=1 mod 3,
//          down-triangle a=b=2 mod 3. Up (a,b) neighbours: (+1,+1),(-2,+1),(+1,-2);
//          down neighbours: (-1,-1),(+2,-1),(-1,+2). Lattice translations are (3s,3t).
// Symmetry group D6 generated by rot: (a,b)->(-b,a+b) and refl: (a,b)->(b,a); both preserve
// the point lattice (hence hexagons) and map triangles to triangles.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#ifndef LAT
#define LAT 6
#endif
#define MAXN 24
static int DUMP=0; static int N; static long long SPLITK=1, SPLITR=0, splitctr=0; static int SPLITDEPTH=6;

#define G (8*MAXN+16)
#define OFF (4*MAXN+8)
static int8_t cella[MAXN], cellb[MAXN];
static uint8_t used[G][G];
static uint64_t fixedcount, freecount, hamcyc, hampath, snake, ouro;
static int a0,b0; // origin

static int cmpcell(const void*p,const void*q){ const int8_t*x=p,*y=q; if(x[0]!=y[0]) return x[0]-y[0]; return x[1]-y[1]; }
static inline int fdiv3(int x){ return (x>=0)? x/3 : -((-x+2)/3); }

static void normalize(int8_t (*c)[2], int n){
  int ma=127,mb=127;
  for(int i=0;i<n;i++){ if(c[i][0]<ma)ma=c[i][0]; if(c[i][1]<mb)mb=c[i][1]; }
#if LAT==6
  for(int i=0;i<n;i++){ c[i][0]-=ma; c[i][1]-=mb; }
#else
  int sa=3*fdiv3(ma), sb=3*fdiv3(mb);
  for(int i=0;i<n;i++){ c[i][0]-=sa; c[i][1]-=sb; }
#endif
  qsort(c,n,2,cmpcell);
}

static inline int adjacent(int a1,int b1,int a2,int b2){
  int da=a2-a1, db=b2-b1;
#if LAT==6
  return (da==1&&db==0)||(da==-1&&db==0)||(da==0&&db==1)||(da==0&&db==-1)||(da==1&&db==-1)||(da==-1&&db==1);
#else
  if(((a1%3)+3)%3==1) return (da==1&&db==1)||(da==-2&&db==1)||(da==1&&db==-2);
  else                return (da==-1&&db==-1)||(da==2&&db==-1)||(da==-1&&db==2);
#endif
}

// ---------- Hamiltonian tests on adjacency bitmasks ----------
static uint32_t adj[MAXN];
static int nverts; static int found; static uint32_t allmask;

// all unvisited vertices reachable from v through unvisited vertices?
static inline int rest_connected(int v, uint32_t visited){
  uint32_t unv = allmask & ~visited;
  if(!unv) return 1;
  uint32_t reach = adj[v] & unv, frontier=reach;
  while(frontier){
    uint32_t nf=0;
    while(frontier){ int u=__builtin_ctz(frontier); frontier&=frontier-1; nf|=adj[u]; }
    nf &= unv & ~reach; reach|=nf; frontier=nf;
  }
  return reach==unv;
}
static void dfs_path(int v, uint32_t visited, int depth){
  if(found) return;
  if(depth==nverts){ found=1; return; }
  if(!rest_connected(v,visited)) return;
  // degree pruning: an unvisited vertex with 0 unvisited neighbours other than v cannot be reached later unless it is the next vertex
  uint32_t unv = allmask & ~visited;
  uint32_t cand = adj[v] & unv;
  {
    // In the remaining path v -> (all of unv), every u in unv except the final vertex has >=2
    // neighbours in unv ∪ {v}; the final vertex has >=1. A vertex whose only available neighbour
    // is v must be both next and last, so it must be the only unvisited vertex.
    uint32_t avail = unv | (1u<<v);
    uint32_t u2=unv; int ones=0;
    while(u2){ int u=__builtin_ctz(u2); u2&=u2-1;
      uint32_t nb=adj[u]&avail; int d=__builtin_popcount(nb);
      if(d==0) return;
      if(d==1){ ones++; if(ones>1) return; if(nb==(1u<<v) && (unv&~(1u<<u))) return; }
    }
  }
  while(cand){ int u=__builtin_ctz(cand); cand&=cand-1;
    dfs_path(u, visited|(1u<<u), depth+1);
    if(found) return;
  }
}
static int has_ham_path(void){
  if(nverts<=2) return 1;
  int leaves=0;
  for(int i=0;i<nverts;i++) if(__builtin_popcount(adj[i])<2) leaves++;
  if(leaves>2) return 0;
  found=0;
  for(int s=0;s<nverts && !found;s++){
    if(leaves>0 && __builtin_popcount(adj[s])>=2) continue;
    dfs_path(s,1u<<s,1);
  }
  return found;
}
static void dfs_cycle(int v, uint32_t visited, int depth){
  if(found) return;
  if(depth==nverts){ if(adj[v]&1u) found=1; return; }
  if(!rest_connected(v,visited)) return;
  uint32_t unv = allmask & ~visited;
  // every unvisited vertex needs >=2 available neighbours among (unvisited ∪ {v} ∪ {start if not yet closed})
  {
    uint32_t avail = unv | (1u<<v) | 1u;
    uint32_t u2=unv;
    while(u2){ int u=__builtin_ctz(u2); u2&=u2-1;
      if(__builtin_popcount(adj[u]&avail)<2) return;
    }
  }
  uint32_t cand = adj[v] & unv;
  while(cand){ int u=__builtin_ctz(cand); cand&=cand-1;
    dfs_cycle(u, visited|(1u<<u), depth+1);
    if(found) return;
  }
}
static int has_ham_cycle(void){
  if(nverts<3) return 0;
  for(int i=0;i<nverts;i++) if(__builtin_popcount(adj[i])<2) return 0;
  found=0; dfs_cycle(0,1u,1); return found;
}

// ---------- process a fixed polyform ----------
// keys: 16-bit packed normalized coordinates (a<<8)|b, sorted ascending = lex order on (a,b)
static inline void make_keys(const int *A, const int *B, int n, uint16_t *key){
  int ma=1<<30, mb=1<<30;
  for(int i=0;i<n;i++){ if(A[i]<ma)ma=A[i]; if(B[i]<mb)mb=B[i]; }
#if LAT==6
  int sa=ma, sb=mb;
#else
  int sa=3*fdiv3(ma), sb=3*fdiv3(mb);
#endif
  for(int i=0;i<n;i++){
    uint16_t k=(uint16_t)(((A[i]-sa)<<8)|(B[i]-sb));
    int j=i; while(j>0 && key[j-1]>k){ key[j]=key[j-1]; j--; } key[j]=k;
  }
}
static void process(void){
  fixedcount++;
  int A[MAXN],B[MAXN],TA[MAXN],TB[MAXN]; uint16_t key[MAXN], tkey[MAXN];
  for(int i=0;i<N;i++){ A[i]=cella[i]; B[i]=cellb[i]; }
  make_keys(A,B,N,key);
  // 12 transforms: rot^k and rot^k∘refl ; c is canonical iff no image is lexicographically smaller
  for(int s=1;s<12;s++){
    int k=s%6, r=s/6;
    for(int i=0;i<N;i++){
      int a=A[i], b=B[i];
      if(r){ int tmp=a; a=b; b=tmp; }
      for(int j=0;j<k;j++){ int na=-b, nb=a+b; a=na; b=nb; }
      TA[i]=a; TB[i]=b;
    }
    make_keys(TA,TB,N,tkey);
    for(int i=0;i<N;i++){ if(tkey[i]<key[i]) return; if(tkey[i]>key[i]) break; }
  }
  freecount++;
  int8_t c[MAXN][2];
  for(int i=0;i<N;i++){ c[i][0]=key[i]>>8; c[i][1]=key[i]&255; }
  nverts=N; allmask=(N==32)?0xffffffffu:((1u<<N)-1);
  for(int i=0;i<N;i++) adj[i]=0;
  for(int i=0;i<N;i++) for(int j=i+1;j<N;j++)
    if(adjacent(c[i][0],c[i][1],c[j][0],c[j][1])){ adj[i]|=1u<<j; adj[j]|=1u<<i; }
  int hc=has_ham_cycle(), hp=has_ham_path();
  if(hc) hamcyc++;
  if(hp) hampath++;
  { int e=0; for(int i=0;i<N;i++) e+=__builtin_popcount(adj[i]); e/=2;
    if(hp && e==N-1) snake++;            // graph is a path
    if(hc && e==N) ouro++; }             // graph is a cycle
  if(DUMP){ for(int i=0;i<N;i++) printf("%d,%d ",c[i][0],c[i][1]); printf("| %d %d\n",hc,hp); }
}

// ---------- Redelmeier ----------
static int untried_a[MAXN*6+10], untried_b[MAXN*6+10];
static inline int allowed(int a,int b){ return b>b0 || (b==b0 && a>=a0); }
static void rec(int depth, int ustart, int uend){
  int myend=uend;
  for(int i=ustart;i<uend;i++){
    int a=untried_a[i], b=untried_b[i];
    cella[depth]=a; cellb[depth]=b;
    if(depth+1==N){ process(); continue; }
    if(depth==SPLITDEPTH && SPLITK>1){ if((splitctr++)%SPLITK!=SPLITR) continue; }
    int saveend=myend;
#if LAT==6
    const int da[6]={1,-1,0,0,1,-1}, db[6]={0,0,1,-1,-1,1}; int nd=6;
#else
    int up = (((a%3)+3)%3==1);
    const int dau[3]={1,-2,1}, dbu[3]={1,1,-2}, dad[3]={-1,2,-1}, dbd[3]={-1,-1,2};
    const int *da = up?dau:dad, *db = up?dbu:dbd; int nd=3;
#endif
    for(int d=0;d<nd;d++){
      int na=a+da[d], nb=b+db[d];
      if(!allowed(na,nb)) continue;
      if(used[nb+OFF][na+OFF]) continue;
      used[nb+OFF][na+OFF]=1; untried_a[myend]=na; untried_b[myend]=nb; myend++;
    }
    rec(depth+1, i+1, myend);
    for(int k=saveend;k<myend;k++) used[untried_b[k]+OFF][untried_a[k]+OFF]=0;
    myend=saveend;
  }
}

static void run_origin(int oa,int ob){
  a0=oa; b0=ob;
  memset(used,0,sizeof used);
  used[ob+OFF][oa+OFF]=1; untried_a[0]=oa; untried_b[0]=ob;
  rec(0,0,1);
}

int main(int argc,char**argv){
  N=atoi(argv[1]); DUMP = getenv("DUMP")!=NULL; if(argc>3){SPLITK=atoll(argv[2]);SPLITR=atoll(argv[3]);} if(argc>4) SPLITDEPTH=atoi(argv[4]);
#if LAT==6
  run_origin(0,0);
#else
  run_origin(1,1);   // lowest cell an up-triangle
  run_origin(2,2);   // lowest cell a down-triangle
#endif
  printf("LAT=%d n=%d fixed=%llu free=%llu hamcycle=%llu hampath=%llu snake=%llu ouroboros=%llu\n",LAT,N,
    (unsigned long long)fixedcount,(unsigned long long)freecount,(unsigned long long)hamcyc,(unsigned long long)hampath,(unsigned long long)snake,(unsigned long long)ouro);
  return 0;
}
